### ISSUE TITLE
Mouse wheel scrolling not working on IE

### ISSUE THREAD

**Issue by yshterev** [PolymerElements/iron-dropdown#101]
### Expected outcome

One should be able to scroll using the mouse wheel
### Actual outcome

Can't scroll `iron-dropdown` content with mouse wheel on IE. Edge is working fine.
### Live Demo

https://jsbin.com/migopa/edit?html,console,output
### Steps to reproduce
1. Click `Open Dropdown` using IE
2. Try scrolling using mouse wheel
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [X] IE 11
- [X] IE 10

Safari not tested.

**Comment by rasto68** [comment]
Just came here to report the same, you can also see the effects of this by visiting the demo page for the element. The workaround for me is to set the 'allow-outside-scroll' attribute if I detect IE but this isn't really ideal :(

**Comment by jhuesos** [comment]
I found the same problem as well. I haven't found a workaround for this issue apart from disabling the scroll lock only for IE11.
