### ISSUE TITLE
sizingTarget property is always overridden

### ISSUE THREAD

**Issue by web-padawan** [PolymerElements/iron-dropdown#102]
### Description
See [line 206](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L206):
```
 this.sizingTarget = this.containedElement || this.sizingTarget;
```
### Expected outcome

I have an `iron-dropdown` with `paper-input` and `paper-listbox` inside. 
Setting `paper-listbox` as `sizingTarget` should make it scrollable while input should stay on top. 

### Actual outcome

The `containedElement` always overrides my config. Shouldn't this look like as follows? 
```
            if (!this.sizingTarget || this.sizingTarget === this) {                
                this.sizingTarget = this.containedElement;
            }

```

BTW `paper-menu-button` also needs to have sizingTarget exposed.

/cc @valdrinkoshi

**Comment by valdrinkoshi** [comment]
Good catch @web-padawan, I think that setting could be done in `attached` instead of `_openedChanged`, as it basically aims to change the default value of `sizingTarget` to be `containedElement`, but needs to wait for the content to be attached.
WDYT? Would you like to send a PR for this? :)
