### ISSUE TITLE
The scrollbar in a dropdown has a pointer cursor instead of a default cursor.

### ISSUE THREAD

**Issue by dschuyler** [PolymerElements/iron-dropdown#109]
The scrollbar in a dropdown has a pointer cursor instead of a default cursor. This appears to happen because the dropdown contents is within the menu button which sets the cursor to the pointer cursor.

### Expected outcome

The mouse cursor is the default cursor on the scrollbar.

### Actual outcome

The mouse cursor is a hand (pointer) cursor on the scrollbar.

### Live Demo
http://jsbin.com/yihuduqezi/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
It looks like the cursor is set by [this line](https://github.com/PolymerElements/paper-dropdown-menu/blob/dd0eb79be7d79d33c041d65fe6877c8da53acee4/paper-dropdown-menu-shared-styles.html#L20) in paper-dropdown-menu/-light's shared styles. Could you try adding a rule like `#content {cursor: auto;}` to each of those instead? I'll have to ask around whether adding that to an 'included' set of styles is considered a breaking change but, at a minimum, this could go in each element individually.
