### ISSUE TITLE
iron-dropdown messes with focused input cursor

### ISSUE THREAD

**Issue by GabiAxel** [PolymerElements/iron-dropdown#11]
When I open iron-dropdown in a component that also contains a focused input element, it becomes impossible to move the cursor using the left/right/backspace keys. Furthermore, when pressing tab to move to the next input, the same behavior happens on that one too, but clicking the input with the mouse fixes it and left/right/backspace become functional again.

This issue does not happen if I use my own element that only extends IronOverlayBehavior instead of iron-dropdown.

Reproduced on latest Chrome and Firefox.

**Comment by cdata** [comment]
Thanks for reporting, I will take a look.

**Comment by miztroh** [comment]
I built an autocomplete component utilizing a ``paper-input`` and an ``iron-dropdown``.  Chrome, IE, Edge, and mobile Safari seem to work fine.  However, when I type within the input and trigger the dropdown in Firefox, focus shifts to the dropdown.

**Comment by valdrinkoshi** [comment]
Closing this as got fixed with the latest `iron-overlay-behavior` (v1.3.2) and `iron-dropdown` (v1.2.0)
http://jsbin.com/sarigi/1/edit?html,output
