### ISSUE TITLE
Why position: fixed instead of position: absolute

### ISSUE THREAD

**Issue by LarsDenBakker** [PolymerElements/iron-dropdown#128]
This element uses iron-overlay-behavior, which causes the dropdown to have position: fixed. 

I understand that it would be useful to have code re-use, but having worked with iron-dropdown a lot in my apps it seems to me like the component would be a lot more stable if position: absolute is used. 

This seems like the more logical and semantic choice for a dropdown, you want to position it in one location and even on scroll it should stay in the same position. You get all the platform benefits across different platforms, old browsers etc. for free. For example there are now quite a lot of expensive recalculations in order to maintain the right position.

But maybe there are reasons that I am overlooking?

**Comment by hzmnet** [comment]
it is big problem used fixed instead absolute

**Comment by learnm90** [comment]
position:absolute

When you specify position:absolute, the element is removed from the document and placed exactly where you tell it to go. 

position:fixed

When you specify position:fixed, the element is fixed to the document and stay fixed where you tell it to go. 
note: on position fixed the element stay fixed meaning that on scroll it stay visible

[see examples and more at Learn More at ammanu:
http://www.ammanu.edu.jo/Learn/Learn1.html](url)

**Comment by LarsDenBakker** [comment]
I understand what positioning properties do, what was not my question. :)

**Comment by Mike2360** [comment]
@learnm90 Thanks for the info.great answer.

**Comment by valdrinkoshi** [comment]
with position: absolute you might end up with clipping problems like this http://jsbin.com/pedaginuze/1/edit?html,output
iron-fit-behavior does set `position: fixed` to avoid these kinds of problems. You can still force it to use `position: absolute` by unsetting `horizontal/vertical-align` and set `position: absolute` via css, e.g.

```html
<style>
  iron-dropdown { position: absolute; top: 0; left: 0 }
</style>
<iron-dropdown horizontal-align="" vertical-align="">
