### ISSUE TITLE
Open/close animations conflict when the configuration is defined directly, rather than via an anonymous function

### ISSUE THREAD

**Issue by iainreid820** [PolymerElements/iron-dropdown#129]
Perhaps this is purely a lack of explicit documentation on exactly how we should provide configuration to the element, but this bug is pretty odd either way. If you supply the configuration for the close and or open animations directly, rather than via an anonymous function, you find that some funky behaviour occurs when switching between instances of that component.

Please see this JSFiddle with examples of the "correct" and "odd" behaviour. The close animations fail to execute when moving from an "odd" to another "odd" element; just click between them and you'll see where I'm coming from:

https://jsfiddle.net/iainreid892/3uyebtf5/

From my own checks this issue is present in at least the following browsers and doesn't appear to be version sensitive:

- Chrome
- Safari
- IE
- Opera
- Firefox

The JSFiddle however only works in Chrome, I'm assuming that this is a limitation of using Polygit in JSFiddle, apologies there.

**Comment by valdrinkoshi** [comment]
From the docs https://www.polymer-project.org/1.0/docs/devguide/properties#configure-values:

> If you provide a function, Polymer calls the function once per element instance.
> 
> When initializing a property to an object or array value, use a function to ensure that each element gets its own copy of the value, rather than having an object or array shared across all instances of the element.

You're seeing weirdness most likely because that animation config is being shared across multiple elements :x
