### ISSUE TITLE
IronDropdownScrollManager does not unregister scroll interaction listeners

### ISSUE THREAD

**Issue by nzacca** [PolymerElements/iron-dropdown#137]
### Description
Line 228 does not unregister the event listeners setup by `_lockScrollInteractions` due to the capture parameters being a new Object. Object equality is performed when unregistering the event and thus the listener is not removed.

### Expected outcome
Listener is removed.

### Actual outcome
Listener is not removed and the event listeners array continues to grow.

### Steps to reproduce
1. Open Chrome Dev Tools.
2. Navigate to the Elements top tab.
3. In the right panel, navigate to the Event Listeners tab.
4. Open and close a paper-dropdown-menu.
5. Refresh the Event Listeners.
6. Note that the `wheel` Event is present.
7. Open and close a paper-dropdown-menu again.
8. Refresh the Event Listeners.
9. Note that there are now 2 wheel Event listeners. This continues the more you click on dropdowns.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by nzacca** [comment]
Fix: https://github.com/nzacca/iron-dropdown/commit/6638de50bf21bda984d10db71c4d6048477a5fb5

**Comment by valdrinkoshi** [comment]
is this still an issue? The manager was moved to iron-overlay-behavior https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-scroll-manager.html#L233

Also, in chrome adding and removing listeners requires only to have the same function reference, but not the same options object reference, e.g. see http://jsbin.com/racobab/edit?html,console,output

**Comment by valdrinkoshi** [comment]
will close for now, feel free to comment here/reopen this in iron-overlay-behavior if the problem persists
