### ISSUE TITLE
Positioning below the trigger element

### ISSUE THREAD

**Issue by govis** [PolymerElements/iron-dropdown#14]
By default the iron-dropdown covers the trigger element. I was wondering if it's possible to achieve classical drop-down layout where it goes below it? It is useful in auto-complete scenarios where the trigger needs to remain visible. In some drop-down menus this layout is preferred as well. So far I've had to wrap it in an extra div to achieve this, but controlling this via verticalAlign property might be cleaner. Thanks.

**Comment by jptrainor** [comment]
+1

**Comment by laurajmaddox** [comment]
+1

**Comment by vertex** [comment]
+1

**Comment by CelineBen** [comment]
+1

**Comment by barnomics** [comment]
+1,000

**Comment by barnomics** [comment]
@govis  would you mind posting a snippet of how you did this somewhere?  I am having a hell of a time trying to creating a simple "dropdown" that isn't fixed to the screen

**Comment by govis** [comment]
I've had success with wrapping it in an extra div:<pre><code>
&lt;!--trigger element such as paper-input or paper-icon-item-->
&lt;paper-something>&lt;/paper-something>
&lt;!--dropdown wrapper-->
&lt;div>
&lt;iron-dropdown id="dropdown">&lt;/iron-dropdown>
&lt;/div>
</code></pre>
This way iron-dropdown tries to cover the wrapper element instead, which is positioned below the actual trigger. Hope this helps.

**Comment by govis** [comment]
And you can also use positionTarget and verticalOffset properties.
