### ISSUE TITLE
iron-dropdown does not replicate native select keyboard nav/a11y behavior

### ISSUE THREAD

**Issue by kaspnilsson** [PolymerElements/iron-dropdown#141]
### Description

iron-dropdown does not replicate native select keyboard nav/a11y behavior

### Expected outcome
I expect the iron-dropdown to natively support keyboard navigation with arrow keys when it is opened.

### Actual outcome
Arrow key events are not caught and handled.

### Example
"Unordered list" in the official demo: https://www.webcomponents.org/element/PolymerElements/iron-dropdown/demo/demo/index.html

**Comment by jrn** [comment]
Workaround: https://gerrit-review.googlesource.com/c/gerrit/+/110380

**Comment by valdrinkoshi** [comment]
iron-dropdown can contain any arbitrary content, so it cannot really update selection since it doesn't know which element is being selected.
You can use `<paper-listbox>` to do that, e.g.
```html
<iron-dropdown>
  <paper-listbox>
     <paper-item>item</paper-item>
     <paper-item>item</paper-item>
  </paper-listbox>
</iron-dropdown>
```
