### ISSUE TITLE
Bug on mobile view

### ISSUE THREAD

**Issue by RoXuS** [PolymerElements/iron-dropdown#143]
### Description
The `iron-dropdown` is closed when the slotted content (`dropdown-content`) is clicked only on mobile view.

It seems an issue from the `iron-overlay-behavior`. In the `iron-overlay-manage.html`. We check if the cursor is outside or inside the slotted content using the `Polymer.dom(event).path`, but on mobile view the value is different.

### Expected outcome
The dropdown shouldn't closes.

### Actual outcome
The dropdown closes.

### Live Demo
http://jsbin.com/xofirixoto/3/edit?html,console,output
Go in device toolbar and choose ipad for example. (In normal desktop view it is ok).

### Browsers Affected

- [x] Chrome

**Comment by valdrinkoshi** [comment]
is this still an issue? i tested on chrome with devtools iphone and could not reproduce

**Comment by RoXuS** [comment]
Hi @valdrinkoshi,

Yes it works as expected now... (https://roxus.github.io/range-datepicker/components/range-datepicker/#/elements/range-datepicker-input/demos/demo/index.html).

Thx.
