### ISSUE TITLE
It's hard to inherit a parent width due to `fixed` positioning

### ISSUE THREAD

**Issue by galanovnick** [PolymerElements/iron-dropdown#146]
### Description
I want to set my dropdown width to its parent width but `fixed` positioning makes it impossible to achieve. I know that you can override this property by using `!important` but this is not my case because I can set styles for `iron-dropdown` only by a mixin.

#### Works, but not my case:
```
iron-dropdown {
  position: absolute !important;
}
```

#### Doesn't work:
```
parent-el {
  --mixin: {
    width: 100%;
    position: absolute !important;
  }
}
...
iron-dropdown {
  @apply --mixin;
}
```

Does `iron-dropdown` really need this `fixed` position property? Would be really nice to have it `absolute` by default.

Related: https://github.com/PolymerElements/iron-dropdown/issues/134, https://github.com/PolymerElements/iron-dropdown/issues/128

### Live Demo
http://jsbin.com/pamerurena/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
The `fixed` positioning is set by `iron-fit-behavior`, which needs to do that in order to position the element according to an arbitrary container (the `positionTarget` property).
You can disable that by unsetting horizontal/vertical-align and use css to position the element yourself, e.g. 
```html
<style>
  iron-dropdown { position: absolute; top: 0; left: 0 }
</style>
<iron-dropdown horizontal-align="" vertical-align="">

**Comment by valdrinkoshi** [comment]
here the updated example http://jsbin.com/vuxufasohi/1/edit?html,output
beware that with `position: absolute` you might end up with clipping problems like this http://jsbin.com/pedaginuze/1/edit?html,output, hence that's why iron-dropdown cannot use that
