### ISSUE TITLE
_fitInfo might not be initialized

### ISSUE THREAD

**Issue by pdelanauze** [PolymerElements/iron-dropdown#19]
https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L328

Getting this stack trace, and my menus cant close : 
```Uncaught TypeError: Cannot set property 'right' of undefined```

Might just require an initialization of `_fitInfo` ?

**Comment by pdelanauze** [comment]
Ah , this actually relates to an 'outdated' version of iron-fit-behavior .. Was using 1.0.0 of iron-fit-behavior, with 1.0.3 I no longer get this issue. Should this dependency be made explicit somewhere in one of the bower.json files ?

**Comment by notwaldorf** [comment]
The elements depend on the "latest" version of other elements, exactly for this reason: to get all bug fix patches as soon as they're available. In all of our `bower.json` files, elements depend on `^1.0.0`, which is "the latest `1.0.x` release" (any release that doesn't have a breaking change).

If you depend on a specific release like 1.0.0, then yes, you will not get bug fixes until you manually bump up the version.

**Comment by pdelanauze** [comment]
agreed.. simplest way to deal with this. but not sure if a simple `bower install` actually upgrades already installed dependencies that match the `#^1.0.0` declaration

**Comment by notwaldorf** [comment]
It should! If that doesn't work, `bower cache clean` should re-giggle the installed cache and then `bower install` will pick them up for sure
