### ISSUE TITLE
Mobile Safari: dropdown doesn't close when tapping outside of it

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/iron-dropdown#21]
Tested on iOS 8.4 in mobile safari.

This results in the other dropdown based elements (paper-menu-button & paper-dropdown-menu) from being closed w/out requiring the user to select an option.

In the case of paper-menu-button & setting the new ignoreActivate property to true, the only way to close the drop down is by programmatically setting opened to false.

**Comment by fozziethebeat** [comment]
I'm also seeing this problem.  Any timeline on fixing this?

**Comment by cdata** [comment]
Hi. I believe this has been fixed. Please re-open if you think the problem is still occurring.
