### ISSUE TITLE
iron-list inside an iron-dropdown

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-dropdown#24]
From https://github.com/PolymerElements/iron-list/issues/76

I am trying to create a component where a user can select a value from a dropdown. In my case the number of values the user can select from can be very large.  Because of this I am trying to put an iron-list inside the dropdown for performance.

When trying this, I'm getting some strange results. I have tried setting a static height and width to both the parent element (iron-list is flex) and iron-list it's self.

Here is an example of the result:
<img width="302" alt="iron-list" src="https://cloud.githubusercontent.com/assets/532441/9429517/7b6644b8-4987-11e5-87b4-ce4e16e2af29.png">

**Comment by cdata** [comment]
@blasten thanks for reporting. Have you had any more insight into the problem since you reported this issue?

**Comment by blasten** [comment]
@cdata yup. iron-dropdown should notify the descendants https://github.com/PolymerElements/iron-resizable-behavior/blob/master/iron-resizable-behavior.html#L90
 before becoming visible and only if it's the right time for measurements.

**Comment by alexdeefuse** [comment]
Hi, another thing that is needed is that "iron-dropdown" implements its own "scroller()" method. Without that iron-list will draw all its elements in one go and use "overflow: auto". Until this is implemented, people can use a container (like paper-header-panel) inside the "iron-dropdown" so the list has something to control its scrolling.

**Comment by valdrinkoshi** [comment]
The issue is still present (first time we open the dropdown) http://jsbin.com/bitalov/5/edit?html,output
