### ISSUE TITLE
Misaligment in an absolutely positioned transformed element

### ISSUE THREAD

**Issue by govis** [PolymerElements/iron-dropdown#30]
iron-dropdown does not seem to align properly in a centrally positioned element with absolute and transform:
<pre><code>
&lt;style>
    .vcenter {
        position: absolute;
        left: 100px;
	    top: 50%;
	    transform: translateY(-50%);
    }
&lt;/style>
&lt;div class="fit relative">
    &lt;div class="vcenter">
        &lt;!--From the iron-dropdown demo page-->
        &lt;x-select>
            &lt;button class="dropdown-trigger">Basic&lt;/button>
            &lt;ul class="dropdown-content" tabindex="0">
                &lt;template is="dom-repeat" items="[[letters]]">
                    &lt;li>&lt;a href="javascript:void(0)">[[item]]&lt;/a>&lt;/li>
                &lt;/template>
            &lt;/ul>
        &lt;/x-select>
    &lt;/div>
&lt;/div>
</code></pre>

![image](https://cloud.githubusercontent.com/assets/971651/10313930/15d2ab08-6c20-11e5-9ce8-d285b43d09d6.png)

**Comment by triglian** [comment]
+ 1

**Comment by cdata** [comment]
Thanks for reporting!

**Comment by cdata** [comment]
The canonical tracking issue for this is https://github.com/PolymerElements/iron-fit-behavior/issues/33, so I am closing this issue.
