### ISSUE TITLE
Additional position/layout options

### ISSUE THREAD

**Issue by govis** [PolymerElements/iron-dropdown#34]
By default when opened too close to the window borders the iron-dropdown is being squeezed and scroll bars added to it. This approach, although pragmatic, may not be very aesthetically pleasing when there's enough real estate exists on the page.

It might be a good idea to consider additional layout options such as:

1. With allow-outside-scroll enabled, one could have the dropdown stick with its positionTarget during page scroll (outside scroll bars would also accommodate any increase in the overall page dimensions added by the dropdown in this case)

2. Another common option could be to adjust the position of the dropdown, sliding it away from the window borders enough to fit it's contents (up-to some pre-set maximum). This can currently be done by setting horizontalOffset and verticalOffset but only after dropdown has opened and it's size is known, so having some sort of a hook for this adjustment or better yet a way to do it automatically would be useful

**Comment by govis** [comment]
Someone has provided a use case in #43

**Comment by josh-infusionsoft** [comment]
+1

**Comment by cdata** [comment]
Yeah, I think that dropdown should magically align itself, if you tell it to.

**Comment by valdrinkoshi** [comment]
This functionality has been provided by `iron-fit-behavior v1.1.0`, check the demo page to see how to set it https://elements.polymer-project.org/elements/iron-fit-behavior?view=demo:demo/index.html&active=Polymer.IronFitBehavior
![iron-fit-behavior](https://cloud.githubusercontent.com/assets/6173664/16673007/ab75a6d4-44aa-11e6-8a64-20be11490e05.gif)
