### ISSUE TITLE
Demo doesn't use iron-dropdown

### ISSUE THREAD

**Issue by binoculars** [PolymerElements/iron-dropdown#37]
It's not even imported. What's going on there?

**Comment by ebidel** [comment]
The demo is confusing since it uses a custom element (x-select). That does use iron-dropdown:

view-source:https://elements.polymer-project.org/bower_components/iron-dropdown/demo/x-select.html

It would be nice if the demo was simpler to understand.

**Comment by binoculars** [comment]
Ah I just was lazy and didn't look deep enough. Thanks @ebidel.
