### ISSUE TITLE
Pinch zooming in Safari allows scrolling the page when overlay is open

### ISSUE THREAD

**Issue by Saulis** [PolymerElements/iron-dropdown#39]
Given the overlay is opened, and the browser window has been _pinch_ zoomed even a little bit in Safari,
When the user scrolls to the bottom of the overlay contents, the page starts to scroll down, although the scroll manager should prevent it.

Tested with Elements Catalog iron-dropdown demo 1.0.6 and Safari 8 + 9.

**Comment by cdata** [comment]
Hi, I totally believe this is a problem. Would you be able to provide a JSBin with a reduced test case?

For more details on filing issues, you can refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md).

**Comment by valdrinkoshi** [comment]
with `iron-dropdown v1.5.0` the scroll gets blocked correctly also when zoomed
![safari-zoom-scroll](https://cloud.githubusercontent.com/assets/6173664/17033260/1aff4f0a-4f32-11e6-8296-16b1c39ce712.gif)
