### ISSUE TITLE
iron-dropdown's position is fixed even when allow-outside-scroll is enabled

### ISSUE THREAD

**Issue by jannakha** [PolymerElements/iron-dropdown#43]
iron-dropdown's position should be set to absolute when page scroll is enabled
if position is fixed, dropdown stays on in the same position even if it's attached to a positionTarget

view without scrolling:
![screen shot 2015-12-23 at 2 23 34 pm](https://cloud.githubusercontent.com/assets/1356783/11970969/dac41d00-a980-11e5-8512-4f29332f633d.png)

view after page scroll:
![screen shot 2015-12-23 at 2 23 45 pm](https://cloud.githubusercontent.com/assets/1356783/11970970/dac887be-a980-11e5-8015-2ff86e204ce3.png)

dropdown should just stay attached to the positionTarget when scrolling

**Comment by josh-infusionsoft** [comment]
+1

**Comment by cdata** [comment]
Yeah, well... we knew this would break, but someone wanted that feature anyway. Thanks for reporting!
