### ISSUE TITLE
Issue affecting paper-dropdown-menu

### ISSUE THREAD

**Issue by felipecesar00** [PolymerElements/iron-dropdown#44]
This issue was reported in the github from paper-dropdown-menu and an user said this issue actually would be from iron-dropdown: https://github.com/PolymerElements/paper-dropdown-menu/issues/95

As I didn't notice any similar issue here, I'm just bringing the problem here to be able to be sure if is a iron-dropdown problem. The problem is affecting me, as every paper-dropdown-menu in my application fires the same scrollbar problem. So, I'm interesting on following the progress of this problem :)

**Comment by cdata** [comment]
Hi, thanks for the book keeping! I have moved that issue to where it belongs: https://github.com/PolymerElements/iron-dropdown/issues/54

Going to close this one out now.
