### ISSUE TITLE
ScollLock stack adds up when opening multiple times 

### ISSUE THREAD

**Issue by rubenstolk** [PolymerElements/iron-dropdown#47]
- When a dropdown is already open and the open is called again `_renderClosed` doesn't get called and thus ScollLock stack contains two items
- Now closing the dropdown removes only one item from the stack
- Result: dropdown is closed but ScrollLock is still active

Solution: call `removeScollLock` in `_renderOpened` before `pushScrollLock`. Sending a PR.

**Comment by cedric-marcone** [comment]
Issue confirmed : This bug is hitting us hard on two apps.
The simple fix works fine for us.
Thanks for reviewing / including this PR.

**Comment by cdata** [comment]
Hi, thanks for reporting! This definitely needs to get fixed ASAP.
