### ISSUE TITLE
demo looks poor due to scrollbar appearing/disappearing

### ISSUE THREAD

**Issue by cdata** [PolymerElements/iron-dropdown#54]
_From @davidmaxwaterman on December 7, 2015 15:0_

1. visit : https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu
2. observe a double scrollbar
3. click on the basic menu menu
4. observe a single scrollbar, as well as a side-ways 'jitter' as the scrollbar appears/disappears.

Please consider fixing it to look better.

_Copied from original issue: PolymerElements/paper-dropdown-menu#95_

**Comment by cdata** [comment]
_From @MeinAccount on December 30, 2015 20:27_

This is essentially an issue of the [`IronDropdownScrollManager`](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown-scroll-manager.html). [I've written a quick fix to prevent the entire page from moving to the right.](https://gist.github.com/MeinAccount/1614c4ae3edcea7d4660)

**Comment by cdata** [comment]
This is totally a problem. It may be sufficient for us to not turn off scroll for the document body (which would fix this for a lot of cases). It needs exploration.

**Comment by bipin-nag** [comment]
What is the reason for hiding overflows - so that user can't use scrollbar while menu is open and the menu does not float on screen while viewer scrolls ?

If so then the iron dropdown position should be absolute not fixed (also needs top and left set properly)

**Comment by ZepAviator** [comment]
Any official fix for this? Seems like a glaring Polymer issue.

**Comment by e111077** [comment]
Hi @ZepAviator, unfortunately, not yet; we are still working on the problem and are weighing fixes that value performance vs fixes that value less intervention.

We are definitely accepting ideas and PRs from the community; take a look at the [open](https://github.com/PolymerElements/iron-dropdown/issues/70) [PRs](https://github.com/PolymerElements/iron-dropdown/issues/64) referencing this issue if you want to join in on the conversation!

**Comment by tjsavage** [comment]
@danbeam is this still causing issues?
