### ISSUE TITLE
position issues with translate transform

### ISSUE THREAD

**Issue by frankstolle** [PolymerElements/iron-dropdown#56]
The fixed position is not correct calculated if you use translation transform. Example can be viewed here: https://jsfiddle.net/sqo9km2q/

**Comment by cdata** [comment]
Hi, thanks for reporting. This is a dupe of https://github.com/PolymerElements/iron-dropdown/issues/56, so I am going to close it.

**Comment by frankstolle** [comment]
Hmm because this is acutally #56, where is the dupe?

**Comment by frankstolle** [comment]
Can you please link the correct issue which is duplicated? You linked the issue itself.

**Comment by cdata** [comment]
Sorry! The correct issue is https://github.com/PolymerElements/iron-fit-behavior/issues/33
