### ISSUE TITLE
Test suite in critical condition due to transitive dependency change.

### ISSUE THREAD

**Issue by cdata** [PolymerElements/iron-dropdown#57]
The change to `iron-overlay-behavior` [here](https://github.com/PolymerElements/iron-overlay-behavior/commit/43f0ca38607846417c972cfc232253ce8637be3e) caused a bunch of failures in the `iron-dropdown` test suite. These should be fixed. It would probably be better to change the tests to listen to open / close events rather than relying on async timing.

**Comment by valdrinkoshi** [comment]
@cdata  this is already addressed in https://github.com/PolymerElements/iron-dropdown/pull/53

**Comment by cdata** [comment]
You rock!
