### ISSUE TITLE
iron-dropdown forces layout on resize when not open

### ISSUE THREAD

**Issue by sorvell** [PolymerElements/iron-dropdown#59]
Layout is forced via https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L382.

If this is not necessary when the dropdown is closed, then it should definitely be avoided. One user saw a synchronous layout cost of ~80ms due to a layout forced by this code.

When the dropdown is opened, it would be best to delay this until rendering will occur via `requestAnimationFrame`.

**Comment by valdrinkoshi** [comment]
Using `requestAnimationFrame` is a good idea, but we should do this in `iron-overlay-behavior`, in such a way that whoever uses it benefits from the change. E.g. wrap `_onIronResize` into a `requestAnimationFrame` block. Opened the issue in here https://github.com/PolymerElements/iron-overlay-behavior/issues/99
