### ISSUE TITLE
`position: fixed` problem with `<iron-dropdown>`

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-dropdown#67]
_From @cdata on January 20, 2016 20:7_

_From @David-Mulder on September 23, 2015 18:50_

In certain cases the menu will be `position: fixed` relative to other positioned elements (however this doesn't always happen for reasons that are beyond me) thus causing the menu to be misplaced/not visible at all.

I have tried my absolute best to make a minimal reproducible case with no luck, however I have been able to create a set of instructions that reproduce the problem:

 1. Install the Polymer Starter Kit
 2. Add `<link rel="import" href="../bower_components/paper-menu-button/paper-menu-button.html">` to `elements.html`
 3. Replace `#drawerToolbar` in `index.html` with: 

    ```
    <paper-toolbar id="drawerToolbar">
        <span class="paper-font-title flex">Menu</span>
        <paper-menu-button horizontal-align="right">
            <paper-icon-button icon="subject" class="dropdown-trigger"></paper-icon-button>
            <div class="dropdown-content">ASDF</div>
        </paper-menu-button>
    </paper-toolbar>
    ```

 4. To see the menu you can make the window narrow enough to be the exact width of the drawer panel.

In both Chrome, Edge and Firefox the menu will not show due to incorrect positioning both with shady DOM and shadow DOM. 

_Copied from original issue: PolymerElements/paper-menu-button#29_

_Copied from original issue: PolymerElements/iron-fit-behavior#33_

**Comment by valdrinkoshi** [comment]
_From @cdata on January 20, 2016 20:7_

_From @generictjohnson on January 20, 2016 19:35_

I've encountered this problem as well. For me, I believe the cause is that iron-dropdown has a parent with the following CSS rule:

`transform: translate3d(0px, 0px, 0px);`

Apparently this parent acts as the offset point for descendants that are `position:fixed`. By using `getBoundingClientRect()`, iron-dropdown assumes the viewport is the offset point in [`_getPositionRect()`](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L258).

What's the recommended way forward? Is this considered a bug in iron-dropdown, or is this where we should be supplying `horizontalOffset` and `verticalOffset` to the iron-dropdown?

**Comment by valdrinkoshi** [comment]
_From @cdata on January 20, 2016 20:7_

Test case: http://output.jsbin.com/xeloka/2

**Comment by mgiuffrida** [comment]
> http://output.jsbin.com/xeloka/2> worming-your-kitten.png

ew...

**Comment by bcalisch** [comment]
I know that this has been closed for a while, but I am still getting this issue on edge only.  I have a component that uses iron-dropdown and paper items.  When that component is placed inside an overlay that is position: fixed, the menu items are not in their normal position.  The exact same component works fine when it is not the child of a position: fixed element.  Do I need to open another issue for this?
