### ISSUE TITLE
horizontalAlign = 'right' and verticalAlign = 'bottom' won't work on mobile

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-dropdown#76]
### Description
If a page is zoomed, or if it is scrollable, `horizontalAlign = 'right'` and `verticalAlign = 'bottom'` won't position the dropdown at the right position.
The issue is caused by the fact that `iron-dropdown` uses `_fitWidth` which corresponds to `window.innerWidth`. When zoomed, the `window.innerWidth` is less than the `document.documentElement.offsetWidth`. This should be updated also in `iron-fit-behavior` (to handle in a separate PR).
See related issue https://bugs.chromium.org/p/chromium/issues/detail?id=602934

### Live Demo
http://jsbin.com/buyudob/14/ (code here http://jsbin.com/buyudob/14/edit?html,output)

### Steps to reproduce

1. Open devtools and enter in mobile device mode, then load the Live Demo
2. Double tap anywhere to zoom in
3. Click on the `iron-dropdown` button, notice wrong positioning

### Browsers Affected
Tested only on chrome
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
Fixed in `iron-dropdown v1.4.0` (actually fixed by `iron-fit-behavior v1.1.1`)

**Comment by marcus7777** [comment]
thank you
