### ISSUE TITLE
Clicking outside of the element is not closing it

### ISSUE THREAD

**Issue by chimarcos** [PolymerElements/iron-dropdown#78]
### Description
`iron-dropdown` does not close when clicking outside of the element on Chrome (Version 50.0.2661.94 m). I've tried on Firefox, Edge and IE11 and it works fine. Am I missing something?

### Live Demo
https://elements.polymer-project.org/elements/iron-dropdown?view=demo:demo/index.html&active=iron-dropdown

### Steps to reproduce

1. Open the dropdown demo page on Chrome.
2. Try to close it by clicking outside.
3. You can still close it using the ESC key.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [x] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
I'm on 51.0.2704.84 and it seems to be working fine there. Any extra details you can provide?

**Comment by marcus7777** [comment]
fine on 50.0.2661.104 (64-bit) too

**Comment by chimarcos** [comment]
I don't have any extra details. The only thing I can say is that I've tested on 4 different PC's with the same version of Chrome and all of them got the same issue but I don't think this is useful :)

I will update Chrome and try again.

**Comment by bicknellr** [comment]
Oh, this might be related to a change to the Web Animations API that landed in Chrome around that time. @chimarcos, can you check your console to see if any errors are thrown while you're using the demo page?

**Comment by chimarcos** [comment]
@bicknellr I updated it already =(

But the good news is it's working fine now. I added a close button just in case users get the same issue.

The version I've tested is 51.0.2704.84 m. I will downgrade Chrome to 50.0.2661.94 m and test it again.

**Comment by valdrinkoshi** [comment]
@chimarcos seems this was related to the change to Web Animations API. Will close this, let me know if the problem persists and I'll re-open it again ;)
