### ISSUE TITLE
iron-dropdown prevents default on paper-input arrow key navigation

### ISSUE THREAD

**Issue by nika-begiashvili** [PolymerElements/iron-dropdown#87]
iron-dropdown prevents default on paper-input arrow key navigation

if you have paper-input inside iron-dropdown than iron-dropdown prevents keydown events for Left and Right keys, I've found out that inside iron-dropdown-scroll-manager is doing that in _scrollInteractionHandler function but I wasn't able to guess what's it for
so if anyone could clarify what that [event.preventDefault();](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown-scroll-manager.html#L188) is doing there maybe we can come up with proper fix

**Comment by valdrinkoshi** [comment]
Hi @nika-begiashvili, that is needed to prevent scrolling outside the dropdown. If the focus is on the input, the event doesn't get prevented http://jsbin.com/vixeci/2/edit?html,console,output
