### ISSUE TITLE
not work always out of the document with 0X0  Height and Width

### ISSUE THREAD

**Issue by hzmnet** [PolymerElements/iron-dropdown#88]
### Live Demo

<iron-dropdown id="dropdown"  horizontal-align="right" vertical-align="top">
       <div class="dropdown-content">Hello!</div>
</iron-dropdown>

this.$.dropdown.toggle();

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by hzmnet** [comment]
<iron-dropdown id="dropdown"  horizontal-align="right" vertical-align="top">
       <div class="dropdown-content">Hello!</div>
</iron-dropdown>

this.$.dropdown.toggle();

**Comment by valdrinkoshi** [comment]
Hi @hzmnet, it is not clear what is the issue. The toggling works as expected http://jsbin.com/laxejig/1/edit?html,output

**Comment by valdrinkoshi** [comment]
Closing as pending response since 15 days
