### ISSUE TITLE
Iron dropdown positioning issues on mobile zoom

### ISSUE THREAD

**Issue by e111077** [PolymerElements/iron-dropdown#90]
### Description
When zoomed in on mobile, the position and size of a `paper-dropdown` is very wrong.

### Expected outcome
when zooming in on mobile, the dropdown should be in the position that is expected.

### Actual outcome
the position is really wonky. See gif:
![android dropdown positioning](https://cloud.githubusercontent.com/assets/5981958/16788265/48a74574-4858-11e6-9c3d-7bf7a4f9bdb0.gif)

### Live Demo
Demo page for `iron-dropdown` shows this issue.

### Steps to reproduce
1. Serve the demo locally
2. chrome://inspect
3. plug in phone
4. open page on phone
5. inspect
6. zoom in on mobile
7. tap on dropdown buttons

### Browsers Affected

- [x] Chrome (android)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
This is an issue of `iron-fit-behavior`'s way to position the element (it doesn't consider the zoom level). Will move it there.

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-fit-behavior#61
