### ISSUE TITLE
Dropdown content should not be clickable while animating

### ISSUE THREAD

**Issue by tgsergeant** [PolymerElements/iron-dropdown#97]
### Description

It is currently possible to click on dropdown content while it is animating in/out. In my opinion, this should not be possible (or, at least, it should be configurable), as it's very easy to accidentally trigger a click on dropdown items while the menu is closing.

The simplest solution is to add `pointer-events: none` to [the `.animating` CSS block](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L57). I'm happy to follow up with a PR for this if you agree it's a good idea.

This bug is based off https://crbug.com/631840.
### Expected outcome

When a dropdown is closing, the items should not be clickable.
### Actual outcome

When a dropdown is closing, the items are clickable.
### Live Demo

https://jsbin.com/mucizemiqe/edit?html,console,output
### Steps to reproduce
1. Open demo link.
2. Click button to open menu
3. Double click 'Share'. 'Share' is logged to the console twice, even though we close the menu after the first one.

There are a bunch of other ways to reproduce - for example, pressing escape and then trying to click the menu button to reopen.
### Browsers Affected
- [x] Chrome
- [x] Firefox

Untested:
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
@tgsergeant this would be a nice enhancement, and the solution you propose should be addressing it very well. Would you like to open a PR for this?
