### ISSUE TITLE
restoreFocusOnClose should not restore focus when clicking outside

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-dropdown#99]
### Description

Setting `restoreFocusOnClose` to true would restore the focus also when clicking on elements outside the dropdown, instead it should restore it only when the dropdown is closed via ESC key.

**Comment by danbeam** [comment]
@tjsavage

**Comment by mgibas** [comment]
Shouldn't it restore focus when dropdown item was clicked as well?

**Comment by valdrinkoshi** [comment]
this was fixed in https://github.com/PolymerElements/iron-overlay-behavior/pull/248
